import type { CoinProfile } from "./coinProfileCatalog";

/** Purpose summaries checked against the linked official project sources. */
export const COMMUNITY_COIN_PROFILES: CoinProfile[] = [
  {
    asset: "SHIB",
    name: "시바이누 (Shiba Inu)",
    summary: "시바이누는 시바견 밈과 커뮤니티에서 출발한 이더리움 기반 프로젝트입니다. SHIB는 생태계를 대표하는 밈 토큰으로, 커뮤니티 활동과 지원되는 서비스의 결제에 사용됩니다.",
    category: "밈·커뮤니티",
    sourceUrl: "https://shib.io/tokens/shib",
    verifiedAt: "2026-09-06",
  },
  {
    asset: "PEPE",
    name: "페페 (Pepe)",
    summary: "PEPE는 개구리 캐릭터 밈을 소재로 한 이더리움 기반 밈 토큰입니다. 인터넷 문화와 커뮤니티의 참여를 중심으로 하며, 공식 사이트는 별도의 실용 기능을 내세우지 않는 오락 목적의 토큰으로 설명합니다.",
    category: "밈·커뮤니티",
    sourceUrl: "https://www.pepe.vip/",
    verifiedAt: "2026-09-06",
  },
  {
    asset: "BONK",
    name: "봉크 (Bonk)",
    summary: "BONK는 솔라나 개발자와 창작자 커뮤니티에 배포되며 시작한 강아지 테마 밈 토큰입니다. 인터넷 문화와 커뮤니티 활동을 연결하며, BONK를 지원하는 디파이·소비자 앱 등에서 유통되는 생태계 자산입니다.",
    category: "밈·커뮤니티",
    sourceUrl: "https://www.bonkcoin.com/about",
    verifiedAt: "2026-09-06",
  },
  {
    asset: "FLOKI",
    name: "플로키 (Floki)",
    summary: "플로키는 밈 커뮤니티에서 출발해 게임, 디파이, 암호자산 교육 서비스로 확장한 프로젝트입니다. FLOKI는 생태계 유틸리티 토큰으로, 대표 게임 Valhalla의 게임 내 경제와 관련 서비스에 사용됩니다.",
    category: "밈·게임",
    sourceUrl: "https://floki.com/",
    verifiedAt: "2026-09-06",
  },
  {
    asset: "WIF",
    name: "도그위프햇 (dogwifhat)",
    summary: "WIF는 모자를 쓴 강아지 이미지를 소재로 한 솔라나 기반 밈 토큰입니다. 밈의 공유와 커뮤니티 참여가 중심이며, 별도 블록체인을 운영하거나 기술 서비스의 수수료를 지불하는 코인으로 소개되지는 않습니다.",
    category: "밈·커뮤니티",
    sourceUrl: "https://dogwifcoin.org/",
    verifiedAt: "2026-09-06",
  },
  {
    asset: "1INCH",
    name: "원인치 (1inch)",
    summary: "1inch는 여러 분산형 거래소의 유동성을 모아 토큰 교환 경로를 찾는 서비스입니다. 1INCH를 거버넌스 계약에 예치하면 의결권을 얻어 운영 제안에 투표하거나 거래를 처리하는 참여자에게 권한을 위임할 수 있습니다.",
    category: "디파이·거래",
    sourceUrl: "https://1inch.com/blog/post/1inch-token-pioneering-defi-governance-and-utility",
    verifiedAt: "2026-09-06",
  },
  {
    asset: "CAKE",
    name: "팬케이크스왑 (PancakeSwap)",
    summary: "팬케이크스왑은 여러 블록체인에서 토큰 교환과 유동성 공급을 지원하는 분산형 거래소입니다. CAKE는 생태계 토큰으로, 보유자가 프로토콜 변경이나 운영 제안에 투표할 때 사용됩니다.",
    category: "디파이·거래",
    sourceUrl: "https://docs.pancakeswap.finance/protocol/voting",
    verifiedAt: "2026-09-06",
  },
  {
    asset: "CRV",
    name: "커브 (Curve)",
    summary: "커브는 유동성 풀을 이용해 자산을 교환하는 디파이 프로토콜입니다. CRV는 관리 토큰으로, 일정 기간 잠가 의결권을 얻고 프로토콜 변경이나 유동성 풀의 토큰 배분 방향에 투표할 때 사용합니다.",
    category: "디파이·거래",
    sourceUrl: "https://docs.curve.finance/assets/pdf/whitepaper_curvedao.pdf",
    verifiedAt: "2026-09-06",
  },
  {
    asset: "COMP",
    name: "컴파운드 (Compound)",
    summary: "컴파운드는 사용자가 암호자산을 공급하거나 담보를 맡기고 대출받을 수 있는 디파이 프로토콜입니다. COMP는 운영 규칙과 시장 추가 같은 변경안을 제안·투표하고 다른 주소에 의결권을 위임하는 관리 토큰입니다.",
    category: "디파이·대출",
    sourceUrl: "https://compound.finance/governance/comp",
    verifiedAt: "2026-09-06",
  },
  {
    asset: "SNX",
    name: "신세틱스 (Synthetix)",
    summary: "신세틱스는 이더리움에서 자산을 보관·정산하면서 무기한 선물 거래를 지원하는 프로토콜입니다. SNX는 운영 제안과 투표에 참여하는 관리 토큰이며, 생태계의 유동성 및 참여 유인 구조에도 사용됩니다.",
    category: "디파이·파생상품",
    sourceUrl: "https://synthetix.io/",
    verifiedAt: "2026-09-06",
  },
  {
    asset: "SUSHI",
    name: "스시 (Sushi)",
    summary: "스시는 토큰 교환과 유동성 공급을 지원하는 분산형 거래 서비스입니다. SUSHI는 생태계의 스테이킹·관리 토큰이며, 예치된 SUSHI를 나타내는 xSUSHI 등을 통해 커뮤니티 의사결정에 참여할 수 있습니다.",
    category: "디파이·거래",
    sourceUrl: "https://www.sushi.com/blog/sushi-bar-is-back",
    verifiedAt: "2026-09-06",
  },
  {
    asset: "GMX",
    name: "지엠엑스 (GMX)",
    summary: "GMX는 유동성 풀을 기반으로 토큰 교환과 무기한 선물 거래를 지원하는 분산형 거래소입니다. GMX 토큰을 스테이킹하면 프로토콜 운영 제안에 투표하거나 의결권을 위임할 수 있습니다.",
    category: "디파이·파생상품",
    sourceUrl: "https://docs.gmx.io/docs/governance/voting-power/",
    verifiedAt: "2026-09-06",
  },
  {
    asset: "RUNE",
    name: "토르체인 (THORChain)",
    summary: "토르체인은 서로 다른 블록체인의 자산을 교환하도록 연결하는 프로토콜입니다. RUNE는 유동성 풀의 공통 정산 자산이며, 노드가 맡기는 보증 자산과 네트워크 수수료 등에 사용됩니다.",
    category: "디파이·상호운용",
    sourceUrl: "https://docs.thorchain.org/understanding-thorchain/rune",
    verifiedAt: "2026-09-06",
  },
  {
    asset: "XLM",
    name: "스텔라 루멘 (Stellar)",
    summary: "스텔라는 여러 통화와 자산을 디지털 형태로 발행하고 전송할 수 있도록 설계된 공개 네트워크입니다. 기본 자산 XLM은 거래 수수료와 계정의 최소 잔액에 사용되어 무분별한 네트워크 사용을 제한합니다.",
    category: "결제·자산 발행",
    sourceUrl: "https://stellar.org/learn/lumens",
    verifiedAt: "2026-09-06",
  },
  {
    asset: "BCH",
    name: "비트코인 캐시 (Bitcoin Cash)",
    summary: "비트코인 캐시는 개인 간 전자현금 결제와 송금을 지향하는 작업증명 네트워크입니다. BCH는 이 네트워크에서 주고받는 기본 화폐이며 거래 수수료에도 사용됩니다. BTC와는 별개의 블록체인 자산입니다.",
    category: "결제·작업증명",
    sourceUrl: "https://bitcoincash.org/",
    verifiedAt: "2026-09-06",
  },
  {
    asset: "HBAR",
    name: "헤데라 (Hedera)",
    summary: "헤데라는 토큰 발행, 스마트 계약, 데이터 기록 등의 서비스를 제공하는 공개 네트워크입니다. HBAR는 서비스 이용 수수료를 내는 기본 자산이며, 스테이킹을 통해 네트워크 보안에도 참여합니다.",
    category: "스마트 계약·인프라",
    sourceUrl: "https://hedera.com/faq/",
    verifiedAt: "2026-09-06",
  },
  {
    asset: "ALGO",
    name: "알고랜드 (Algorand)",
    summary: "알고랜드는 결제, 자산 발행, 스마트 계약을 지원하는 지분증명 블록체인입니다. ALGO는 자금 전송과 거래 수수료에 쓰이는 기본 자산이며, 참여 노드의 합의 과정에서도 사용됩니다.",
    category: "스마트 계약·인프라",
    sourceUrl: "https://algorand.co/technology/the-algo",
    verifiedAt: "2026-09-06",
  },
  {
    asset: "ICP",
    name: "인터넷 컴퓨터 (Internet Computer)",
    summary: "인터넷 컴퓨터는 앱의 계산과 데이터 저장을 블록체인에서 실행하는 네트워크입니다. ICP를 잠가 운영 제안에 투표할 수 있으며, 앱 실행·저장 비용을 지불하는 별도 단위인 사이클로 전환할 수 있습니다.",
    category: "분산 컴퓨팅",
    sourceUrl: "https://docs.internetcomputer.org/concepts/governance/",
    verifiedAt: "2026-09-06",
  },
  {
    asset: "KAS",
    name: "카스파 (Kaspa)",
    summary: "카스파는 작업증명과 여러 블록을 병렬로 연결하는 블록DAG 구조를 사용하는 공개 네트워크입니다. KAS는 이 네트워크에서 가치를 전송하는 기본 코인이며, 채굴을 통해 발행됩니다.",
    category: "작업증명·인프라",
    sourceUrl: "https://kaspa.org/",
    verifiedAt: "2026-09-06",
  },
  {
    asset: "VET",
    name: "비체인 (VeChain)",
    summary: "비체인은 자산 전송과 앱 실행을 지원하는 VeChainThor 블록체인입니다. VET는 가치 전송과 네트워크 보안을 위한 스테이킹에 쓰입니다. 거래 수수료는 VET 자체가 아닌 별도 토큰 VTHO로 지불합니다.",
    category: "스마트 계약·인프라",
    sourceUrl: "https://vechain.org/get-started/buy-vet",
    verifiedAt: "2026-09-06",
  },
];
