import type { CoinProfile } from "./coinProfileCatalog";

// Original Korean summaries checked against each project's primary documentation.
// Asset keys are explicit exchange tickers; legacy or similarly named tokens are not aliases.
export const EXTENDED_COIN_PROFILES: CoinProfile[] = [
  {
    asset: "APT",
    name: "Aptos",
    summary: "Move 언어로 스마트 계약과 앱을 만드는 레이어1 블록체인입니다. APT는 거래 수수료를 내고, 검증인에게 예치해 네트워크 보안을 지원하며, 프로토콜 변경 투표에 참여하는 데 쓰입니다.",
    category: "레이어1",
    sourceUrl: "https://aptosfoundation.org/whitepaper/aptos-whitepaper_en.pdf",
    verifiedAt: "2026-09-06",
  },
  {
    asset: "INJ",
    name: "Injective",
    summary: "거래소 등 금융 앱을 만들 수 있도록 주문장과 거래 기능을 제공하는 레이어1 블록체인입니다. INJ는 네트워크 수수료, 검증인 스테이킹, 운영 규칙에 대한 거버넌스 투표에 쓰입니다.",
    category: "금융 블록체인",
    sourceUrl: "https://docs.injective.network/defi/tokens/inj-coin",
    verifiedAt: "2026-09-06",
  },
  {
    asset: "RENDER",
    name: "Render Network",
    summary: "GPU를 제공하는 운영자와 렌더링·컴퓨팅 작업이 필요한 이용자를 연결합니다. 이용자는 RENDER를 소각해 작업용 크레딧을 받고, GPU 작업을 수행한 노드는 네트워크가 발행하는 RENDER를 보상으로 받습니다.",
    category: "분산 GPU",
    sourceUrl: "https://know.rendernetwork.com/basics/the-render-spl-token",
    verifiedAt: "2026-09-06",
  },
  {
    asset: "FIL",
    name: "Filecoin",
    summary: "파일을 맡기는 이용자와 저장 공간 제공자를 연결하는 분산 저장 네트워크입니다. 저장 제공자는 데이터를 보관한다는 증명을 제출합니다. FIL은 저장 비용과 제공자의 담보, 네트워크 수수료에 쓰입니다.",
    category: "분산 저장",
    sourceUrl: "https://docs.filecoin.io/basics/what-is-filecoin",
    verifiedAt: "2026-09-06",
  },
  {
    asset: "ETC",
    name: "Ethereum Classic",
    summary: "작업증명 방식의 채굴로 거래를 검증하며 스마트 계약을 실행하는 블록체인입니다. ETC는 송금과 스마트 계약 실행에 필요한 수수료를 지불하고, 블록을 만드는 채굴자에게 보상하는 데 쓰입니다.",
    category: "레이어1",
    sourceUrl: "https://ethereumclassic.org/faqs/users/",
    verifiedAt: "2026-09-06",
  },
  {
    asset: "TRX",
    name: "TRON",
    summary: "토큰 송금과 스마트 계약을 실행하는 블록체인입니다. TRX를 예치하면 거래·연산에 필요한 대역폭과 에너지를 확보하고 대표 검증인 선거에 투표할 수 있습니다. 자원이 부족한 거래는 TRX를 소모해 처리합니다.",
    category: "레이어1",
    sourceUrl: "https://developers.tron.network/docs/resource-model",
    verifiedAt: "2026-09-06",
  },
  {
    asset: "POL",
    name: "Polygon Ecosystem Token",
    summary: "이더리움과 연결된 Polygon PoS에서 앱과 스마트 계약을 실행할 때 사용하는 기본 토큰입니다. POL은 거래 수수료를 지불하고 검증인에게 예치해 네트워크 보안을 지원하는 데 쓰입니다.",
    category: "블록체인 확장",
    sourceUrl: "https://docs.polygon.technology/pos/concepts/tokens/pol",
    verifiedAt: "2026-09-06",
  },
  {
    asset: "LDO",
    name: "Lido DAO",
    summary: "Lido는 ETH를 예치한 이용자에게 예치 지분을 나타내는 stETH를 제공하는 유동성 스테이킹 프로토콜입니다. LDO는 수수료와 운영 설정 등 Lido DAO의 주요 결정을 투표하는 거버넌스 토큰입니다.",
    category: "유동성 스테이킹",
    sourceUrl: "https://docs.lido.fi/guides/lido-tokens-integration-guide/",
    verifiedAt: "2026-09-06",
  },
  {
    asset: "DYDX",
    name: "dYdX",
    summary: "자체 블록체인의 주문장으로 무기한 선물 거래를 지원하는 탈중앙 거래 프로토콜입니다. dYdX Chain의 DYDX는 검증인에게 예치해 네트워크 보안을 지원하고 시장 상장·운영 규칙 투표에 참여하는 데 쓰입니다.",
    category: "탈중앙 파생상품",
    sourceUrl: "https://www.dydx.foundation/blog/dydx-token-utility-explaned",
    verifiedAt: "2026-09-06",
  },
  {
    asset: "JUP",
    name: "Jupiter",
    summary: "Solana의 여러 거래소에서 교환 경로를 찾아 토큰 스왑을 연결하고 파생상품 등 거래 도구를 제공합니다. JUP는 Jupiter DAO의 거버넌스 토큰으로, 예치한 토큰을 통해 생태계 관련 제안에 투표합니다.",
    category: "탈중앙 거래",
    sourceUrl: "https://docs.jup.ag/user-docs/more/jup-token/tokenomics",
    verifiedAt: "2026-09-06",
  },
  {
    asset: "SEI",
    name: "Sei",
    summary: "이더리움 앱과 호환되는 실행 환경과 병렬 처리에 초점을 둔 레이어1 블록체인입니다. SEI는 거래 수수료를 내고, 검증인에게 예치해 네트워크를 운영하며, 프로토콜 변경 투표에 참여하는 데 쓰입니다.",
    category: "레이어1",
    sourceUrl: "https://docs.sei.io/learn/sei-giga",
    verifiedAt: "2026-09-06",
  },
  {
    asset: "FET",
    name: "Artificial Superintelligence Alliance",
    summary: "Fetch.ai의 AI 에이전트가 서비스를 찾고 서로 작업·결제를 수행하도록 돕는 생태계의 토큰입니다. FET는 에이전트 서비스와 네트워크 수수료 지불에 쓰이며, 기본 네트워크의 FET는 검증인 스테이킹에도 사용됩니다.",
    category: "AI 에이전트",
    sourceUrl: "https://network.fetch.ai/docs/introduction/native-and-erc-fet",
    verifiedAt: "2026-09-06",
  },
  {
    asset: "TAO",
    name: "Bittensor",
    summary: "AI와 컴퓨팅 작업을 수행하는 여러 하위 네트워크에서 제공자의 결과를 검증하고 기여에 보상하는 네트워크입니다. TAO는 공통 기본 토큰으로, 스테이킹과 하위 네트워크 토큰 교환·유동성 구조에 쓰입니다.",
    category: "분산 AI",
    sourceUrl: "https://docs.learnbittensor.org/dynamic-tao/dtao-guide",
    verifiedAt: "2026-09-06",
  },
  {
    asset: "GRT",
    name: "The Graph",
    summary: "블록체인 데이터를 앱이 쉽게 검색하도록 정리하고 조회 요청에 응답하는 분산 인덱싱 프로토콜입니다. GRT는 데이터 제공 노드의 예치·위임, 조회 수수료와 데이터 인덱싱 보상에 쓰입니다.",
    category: "데이터 인덱싱",
    sourceUrl: "https://thegraph.com/docs/en/resources/tokenomics/",
    verifiedAt: "2026-09-06",
  },
  {
    asset: "PYTH",
    name: "Pyth Network",
    summary: "시장 가격 데이터를 모아 여러 블록체인의 앱에 전달하는 오라클 네트워크입니다. PYTH는 토큰을 예치한 참여자가 데이터 제공과 운영 규칙 등에 관한 Pyth DAO 제안에 투표하는 데 쓰입니다.",
    category: "오라클",
    sourceUrl: "https://docs.pyth.network/pyth-token",
    verifiedAt: "2026-09-06",
  },
  {
    asset: "ENA",
    name: "Ethena",
    summary: "암호자산과 선물 매도 포지션 등을 조합해 합성 달러 USDe를 운영하는 프로토콜입니다. ENA는 위험위원회 선출 등 Ethena의 주요 의사결정에 참여하는 거버넌스 토큰입니다.",
    category: "합성 달러 프로토콜",
    sourceUrl: "https://docs.ethena.fi/ena",
    verifiedAt: "2026-09-06",
  },
  {
    asset: "ONDO",
    name: "Ondo",
    summary: "실물 금융자산의 토큰화와 관련 온체인 금융 서비스를 지원하는 Ondo 생태계의 거버넌스 토큰입니다. ONDO는 Ondo DAO와 대출 프로토콜 Flux Finance의 제안·운영 결정에 쓰입니다.",
    category: "실물자산·거버넌스",
    sourceUrl: "https://docs.ondo.foundation/ondo-token",
    verifiedAt: "2026-09-06",
  },
  {
    asset: "PENDLE",
    name: "Pendle",
    summary: "수익이 발생하는 자산을 원금 부분인 PT와 만기까지의 수익 부분인 YT로 나눠 거래하는 프로토콜입니다. PENDLE을 예치해 받은 sPENDLE은 프로토콜 제안 투표와 참여 조건에 따른 보상 분배에 쓰입니다.",
    category: "수익 분리·거래",
    sourceUrl: "https://docs.pendle.finance/pendle-v2/ProtocolMechanics/Mechanisms/sPENDLE",
    verifiedAt: "2026-09-06",
  },
  {
    asset: "TIA",
    name: "Celestia",
    summary: "다른 블록체인과 롤업이 거래 데이터를 공개·검증할 수 있도록 데이터 가용성 공간을 제공하는 모듈형 네트워크입니다. TIA는 데이터 게시 비용, 검증인 스테이킹, 네트워크 운영 규칙 투표에 쓰입니다.",
    category: "데이터 가용성",
    sourceUrl: "https://docs.celestia.org/learn/TIA/overview/",
    verifiedAt: "2026-09-06",
  },
  {
    asset: "AR",
    name: "Arweave",
    summary: "한 번의 저장 비용으로 데이터를 장기간 보존하도록 설계된 분산 저장 프로토콜입니다. AR은 데이터 기록 수수료에 쓰이며, 비용 일부는 저장 기금에 쌓여 데이터를 유지하는 채굴자에게 지급됩니다.",
    category: "분산 저장",
    sourceUrl: "https://www.arweave.org/yellow-paper.pdf",
    verifiedAt: "2026-09-06",
  },
  {
    asset: "STORJ",
    name: "Storj",
    summary: "파일을 분산된 저장 노드에 나눠 보관하는 클라우드 저장 서비스입니다. STORJ는 저장 공간과 전송 대역폭을 제공한 노드 운영자에게 지급하는 토큰이며, 이용자의 저장 서비스 결제에도 쓰입니다.",
    category: "분산 저장",
    sourceUrl: "https://www.storj.io/blog/storj-fully-evm-compatible-decentralized-storage-for-ethereum-and-l2-applications",
    verifiedAt: "2026-09-06",
  },
  {
    asset: "JASMY",
    name: "JasmyCoin",
    summary: "개인이 데이터 보관함을 통해 자신의 정보와 IoT 데이터를 관리하고 공유 범위를 정하도록 돕는 프로젝트입니다. JASMY는 이더리움 기반 토큰으로, 생태계의 데이터 관련 서비스와 작업에 대한 가치 교환·결제용으로 설계됐습니다.",
    category: "개인 데이터·IoT",
    sourceUrl: "https://www.jasmy.co.jp/images/company/Jasmy-Whitepaper.pdf",
    verifiedAt: "2026-09-06",
  },
  {
    asset: "IOTX",
    name: "IoTeX",
    summary: "실제 기기와 데이터를 블록체인 앱에 연결하는 DePIN 프로젝트를 지원하는 네트워크입니다. IOTX는 송금·스마트 계약 수수료를 내고 검증인을 선택하는 스테이킹, 프로토콜 의사결정에 쓰입니다.",
    category: "기기·DePIN",
    sourceUrl: "https://cdn.iotex.io/whitepaper/iotex_whitepaper_eu.pdf",
    verifiedAt: "2026-09-06",
  },
  {
    asset: "ENS",
    name: "Ethereum Name Service",
    summary: "긴 지갑 주소나 콘텐츠 주소를 alice.eth처럼 읽기 쉬운 이름에 연결하는 이름 서비스입니다. ENS 토큰은 이름 자체와 별개로, ENS DAO의 주요 운영·재정 결정을 제안하고 투표하는 데 쓰입니다.",
    category: "블록체인 이름 서비스",
    sourceUrl: "https://docs.ens.domains/dao/token/",
    verifiedAt: "2026-09-06",
  },
  {
    asset: "API3",
    name: "Api3",
    summary: "API 데이터 제공자가 직접 운영하는 오라클을 통해 외부 정보를 스마트 계약에 전달하는 프로젝트입니다. API3 토큰을 DAO 풀에 예치하면 지원금 배분과 운영 설정 등 거버넌스 제안·투표에 참여할 수 있습니다.",
    category: "오라클",
    sourceUrl: "https://dao-docs.api3.org/overview/governance.html",
    verifiedAt: "2026-09-06",
  },
];
