from pathlib import Path

root = Path('/home/ubuntu/korea-stock-sector-analyzer')
home = root / 'client/src/pages/Home.tsx'
text = home.read_text()
text = text.replace('type SortKey = "marketRank" | "name" | "code" | "sector" | "marketSuffix" | "currentPrice" | "annualEps" | "earningsYield" | "lastPriceFetchedAt";', 'type SortKey = "marketRank" | "name" | "code" | "sector" | "marketSuffix" | "currentPrice" | "annualEps" | "earningsYield" | "per" | "pbr" | "marketCapHundredMillionKrw" | "latestOperatingProfitHundredMillionKrw" | "connectionStatus" | "lastPriceFetchedAt";')
text = text.replace('const TABLE_PAGE_SIZE = 25;', 'const TABLE_PAGE_SIZE = 25;\nconst SUMMARY_SORT_KEYS = new Set<SortKey>(["per", "pbr", "marketCapHundredMillionKrw", "latestOperatingProfitHundredMillionKrw"]);')
text = text.replace('const allSectorMeta = {\n  key: "all" as const,\n  label: "KOSPI 200 전체",\n  shortLabel: "전체 200",\n  description: "KOSPI 시가총액 상위 200개 전체를 자체 테마와 함께 한 번에 비교합니다.",\n};', 'const allSectorMeta = {\n  key: "all" as const,\n  label: "국내주식 전체",\n  shortLabel: "국내 전체",\n  description: "국내 대표 종목 전체를 자체 테마와 함께 한 번에 비교합니다.",\n};')
text = text.replace('    if (!sortState) return list;\n\n    const getSortValue = (row: (typeof list)[number]) => {', '    if (!sortState || SUMMARY_SORT_KEYS.has(sortState.key)) return list;\n\n    const getSortValue = (row: (typeof list)[number]) => {')
text = text.replace('        case "earningsYield": return row.earningsYield ?? Number.NEGATIVE_INFINITY;\n        case "lastPriceFetchedAt": return row.lastPriceFetchedAt ? new Date(row.lastPriceFetchedAt).getTime() : Number.NEGATIVE_INFINITY;', '        case "earningsYield": return row.earningsYield ?? Number.NEGATIVE_INFINITY;\n        case "connectionStatus": return getConnectionLabel(row.dataSource, row.currentPrice, row.annualEps);\n        case "lastPriceFetchedAt": return row.lastPriceFetchedAt ? new Date(row.lastPriceFetchedAt).getTime() : Number.NEGATIVE_INFINITY;')
text = text.replace('  const summaryByCode = useMemo(() => new Map((financialSummaries.data ?? []).map(summary => [summary.code, summary])), [financialSummaries.data]);', '''  const summaryByCode = useMemo(() => new Map((financialSummaries.data ?? []).map(summary => [summary.code, summary])), [financialSummaries.data]);\n  const pagedDisplayRows = useMemo(() => {\n    if (!sortState || !SUMMARY_SORT_KEYS.has(sortState.key)) return pagedRows;\n\n    const getSummarySortValue = (row: (typeof pagedRows)[number]) => {\n      const summary = summaryByCode.get(row.code.padStart(6, "0"));\n      if (!summary?.success) return null;\n      switch (sortState.key) {\n        case "per": return summary.per;\n        case "pbr": return summary.pbr;\n        case "marketCapHundredMillionKrw": return summary.marketCapHundredMillionKrw;\n        case "latestOperatingProfitHundredMillionKrw": return summary.latestOperatingProfitHundredMillionKrw;\n        default: return null;\n      }\n    };\n\n    return [...pagedRows].sort((a, b) => {\n      const aValue = getSummarySortValue(a);\n      const bValue = getSummarySortValue(b);\n      const aMissing = aValue === null || !Number.isFinite(aValue);\n      const bMissing = bValue === null || !Number.isFinite(bValue);\n      if (aMissing && bMissing) return (a.marketRank ?? 999999) - (b.marketRank ?? 999999);\n      if (aMissing) return 1;\n      if (bMissing) return -1;\n      const compared = Number(aValue) - Number(bValue);\n      return sortState.direction === "asc" ? compared : -compared;\n    });\n  }, [pagedRows, sortState, summaryByCode]);''')
text = text.replace('    EPS/주가: "EPS/주가",\n    lastPriceFetchedAt: "갱신시각",', '    EPS/주가: "EPS/주가",\n    per: "PER",\n    pbr: "PBR",\n    marketCapHundredMillionKrw: "시가총액",\n    latestOperatingProfitHundredMillionKrw: "영업이익",\n    connectionStatus: "연동 상태",\n    lastPriceFetchedAt: "갱신시각",')
# Above replacement target contains Korean key line; fix exact original if not replaced
text = text.replace('    earningsYield: "EPS/주가",\n    lastPriceFetchedAt: "갱신시각",', '    earningsYield: "EPS/주가",\n    per: "PER",\n    pbr: "PBR",\n    marketCapHundredMillionKrw: "시가총액",\n    latestOperatingProfitHundredMillionKrw: "영업이익",\n    connectionStatus: "연동 상태",\n    lastPriceFetchedAt: "갱신시각",')
text = text.replace('          <Badge className="mb-5 bg-slate-950 text-white hover:bg-slate-950">KOSPI Top 200 Theme Dashboard</Badge>', '          <Badge className="mb-5 bg-slate-950 text-white hover:bg-slate-950">Domestic Stock Sector Dashboard</Badge>')
text = text.replace('            KOSPI 200 밸류에이션·실적 테마 분석', '            국내주식 섹터분석')
text = text.replace('            KOSPI 시가총액 상위 200개 종목을 자체 산업·비즈니스 테마로 재분류하고, 종목 클릭 시 PER, PBR, 시가총액, 영업이익, EPS, EPS/주가(%), 최근 분기별 실적과 RSI 등 대표 보조지표 10개를 한 화면에서 확인하도록 정리했습니다.', '            국내 대표 종목을 자체 산업·비즈니스 테마로 재분류하고, 종목 클릭 시 PER, PBR, 시가총액, 영업이익, EPS, EPS/주가(%), 최근 분기별 실적과 RSI 등 대표 보조지표를 한 화면에서 확인하도록 정리했습니다.')
text = text.replace('                현재 정렬: <span className="font-black text-slate-900">{currentSortLabel}</span> · 최신 화면 표식: KOSPI 200 테마, PER 별도, PBR 별도, RSI. 폭이 좁은 화면과 크롬 확대 상태에서는 표 영역만 좌우로 밀어 보세요. 공개 사이트가 이전 EPS 화면으로 보이면 Ctrl+Shift+R로 강력 새로고침하세요.', '                현재 정렬: <span className="font-black text-slate-900">{currentSortLabel}</span> · 최신 화면 표식: 국내주식 테마, PER 별도, PBR 별도, RSI. PER·PBR·시가총액·영업이익은 현재 페이지에 조회된 재무 요약값 기준으로 정렬합니다. 폭이 좁은 화면과 크롬 확대 상태에서는 표 영역만 좌우로 밀어 보세요.')
text = text.replace('                  <th className="px-3 py-2 text-right font-medium">PER</th>\n                  <th className="px-3 py-2 text-right font-medium">PBR</th>\n                  <th className="px-4 py-2 text-right font-medium">시가총액·실적</th>\n                  <th className="px-4 py-2 font-medium">연동 상태</th>', '                  <th className="px-2 py-2">{sortableHeader("PER", "per", "right")}</th>\n                  <th className="px-2 py-2">{sortableHeader("PBR", "pbr", "right")}</th>\n                  <th className="px-2 py-2">{sortableHeader("시가총액", "marketCapHundredMillionKrw", "right")}</th>\n                  <th className="px-2 py-2">{sortableHeader("영업이익", "latestOperatingProfitHundredMillionKrw", "right")}</th>\n                  <th className="px-2 py-2">{sortableHeader("연동 상태", "connectionStatus")}</th>')
text = text.replace('                {pagedRows.map(row => {', '                {pagedDisplayRows.map(row => {')
text = text.replace('                      {summary?.success ? (\n                        <div className="space-y-1 whitespace-nowrap">\n                          <p className="font-black text-slate-950">{formatHundredMillionKrw(summary.marketCapHundredMillionKrw)}</p>\n                          <p>영업이익 {formatHundredMillionKrw(summary.latestOperatingProfitHundredMillionKrw)}</p>\n                        </div>\n                      ) : summaryLoading ? <span className="text-slate-400">조회 중</span> : summary && !summary.success ? <button type="button" className="rounded-full bg-slate-100 px-2 py-1 text-slate-600 transition hover:bg-blue-50 hover:text-blue-700" onClick={(event) => { event.stopPropagation(); setSelectedStock(row); }} aria-label={`${row.name} 상세 실적 다시 조회`}>상세 조회</button> : <span className="text-slate-400">대기</span>}\n                    </td>\n                    <td className="px-4 py-3"><Badge variant="outline" className="rounded-full bg-white">{getConnectionLabel(row.dataSource, row.currentPrice, row.annualEps)}</Badge></td>', '                      {summary?.success ? (\n                        <p className="font-black text-slate-950 whitespace-nowrap">{formatHundredMillionKrw(summary.marketCapHundredMillionKrw)}</p>\n                      ) : summaryLoading ? <span className="text-slate-400">조회 중</span> : summary && !summary.success ? <button type="button" className="rounded-full bg-slate-100 px-2 py-1 text-slate-600 transition hover:bg-blue-50 hover:text-blue-700" onClick={(event) => { event.stopPropagation(); setSelectedStock(row); }} aria-label={`${row.name} 시가총액 상세 다시 조회`}>상세 조회</button> : <span className="text-slate-400">대기</span>}\n                    </td>\n                    <td className="px-4 py-3 text-right text-xs text-slate-700" title={summary && !summary.success ? summary.error : undefined}>\n                      {summary?.success ? (\n                        <p className="font-semibold whitespace-nowrap">{formatHundredMillionKrw(summary.latestOperatingProfitHundredMillionKrw)}</p>\n                      ) : summaryLoading ? <span className="text-slate-400">조회 중</span> : summary && !summary.success ? <button type="button" className="rounded-full bg-slate-100 px-2 py-1 text-slate-600 transition hover:bg-blue-50 hover:text-blue-700" onClick={(event) => { event.stopPropagation(); setSelectedStock(row); }} aria-label={`${row.name} 영업이익 상세 다시 조회`}>상세 조회</button> : <span className="text-slate-400">대기</span>}\n                    </td>\n                    <td className="px-4 py-3"><Badge variant="outline" className="rounded-full bg-white">{getConnectionLabel(row.dataSource, row.currentPrice, row.annualEps)}</Badge></td>')
home.write_text(text)

# App routing patch
app = root / 'client/src/App.tsx'
app_text = app.read_text()
app_text = app_text.replace('import Home from "./pages/Home";', 'import Home from "./pages/Home";\nimport GlobalStocks from "./pages/GlobalStocks";\nimport CryptoSectors from "./pages/CryptoSectors";')
app_text = app_text.replace('<Route path={"/"} component={Home} />\n        <Route path={"/404"} component={NotFound} />', '<Route path={"/"} component={Home} />\n        <Route path={"/global-stocks"} component={GlobalStocks} />\n        <Route path={"/crypto-sectors"} component={CryptoSectors} />\n        <Route path={"/404"} component={NotFound} />')
app.write_text(app_text)

# Dashboard menu patch
dash = root / 'client/src/components/DashboardLayout.tsx'
dash_text = dash.read_text()
dash_text = dash_text.replace('import { BarChart3, LogOut, PanelLeft } from "lucide-react";', 'import { BarChart3, Bitcoin, Globe2, LogOut, PanelLeft } from "lucide-react";')
dash_text = dash_text.replace('const menuItems = [\n  { icon: BarChart3, label: "섹터 분석", path: "/" },\n];', 'const menuItems = [\n  { icon: BarChart3, label: "국내주식 섹터분석", path: "/" },\n  { icon: Globe2, label: "해외주식 섹터분석", path: "/global-stocks" },\n  { icon: Bitcoin, label: "크립토 섹터분석", path: "/crypto-sectors" },\n];')
dash_text = dash_text.replace('대한민국 주식 섹터 분석 도구는 인증된 사용자에게만 제공됩니다. 오너는 종목 데이터 편집과 현재가 갱신 기능을 사용할 수 있습니다.', '국내주식, 해외주식, 크립토 섹터 분석 도구는 인증된 사용자에게만 제공됩니다. 오너는 국내 종목 데이터 편집과 현재가 갱신 기능을 사용할 수 있습니다.')
dash.write_text(dash_text)

# Placeholder pages to keep routes buildable; later phases replace with live tables.
(root / 'client/src/pages/GlobalStocks.tsx').write_text('''import { Badge } from "@/components/ui/badge";\nimport { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";\nimport { Globe2 } from "lucide-react";\n\nexport default function GlobalStocks() {\n  return (\n    <div className="min-h-[calc(100vh-3rem)] rounded-[2rem] bg-[#f7f9fb] p-6 text-slate-950 md:p-8">\n      <Badge className="mb-5 bg-slate-950 text-white hover:bg-slate-950">Global Equity Sector Dashboard</Badge>\n      <Card className="rounded-[2rem] border-0 bg-white/90 shadow-[0_24px_80px_rgba(15,23,42,0.06)]">\n        <CardHeader>\n          <CardTitle className="flex items-center gap-2 text-3xl font-black tracking-tight">\n            <Globe2 className="h-7 w-7 text-blue-500" /> 해외주식 섹터분석\n          </CardTitle>\n          <CardDescription>대표 미국주식 100개 섹터 테이블을 구성하는 중입니다. 다음 단계에서 실시간 요약 카드와 정렬 가능한 분석 표가 연결됩니다.</CardDescription>\n        </CardHeader>\n        <CardContent className="rounded-3xl bg-slate-50 p-6 text-sm font-medium text-slate-600">\n          미국 대형주 100개를 기술, 커뮤니케이션, 헬스케어, 금융, 소비재, 에너지 등 섹터로 비교하도록 확장합니다.\n        </CardContent>\n      </Card>\n    </div>\n  );\n}\n''')
(root / 'client/src/pages/CryptoSectors.tsx').write_text('''import { Badge } from "@/components/ui/badge";\nimport { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";\nimport { Bitcoin } from "lucide-react";\n\nexport default function CryptoSectors() {\n  return (\n    <div className="min-h-[calc(100vh-3rem)] rounded-[2rem] bg-[#f7f9fb] p-6 text-slate-950 md:p-8">\n      <Badge className="mb-5 bg-slate-950 text-white hover:bg-slate-950">Crypto Futures Sector Dashboard</Badge>\n      <Card className="rounded-[2rem] border-0 bg-white/90 shadow-[0_24px_80px_rgba(15,23,42,0.06)]">\n        <CardHeader>\n          <CardTitle className="flex items-center gap-2 text-3xl font-black tracking-tight">\n            <Bitcoin className="h-7 w-7 text-amber-500" /> 크립토 섹터분석\n          </CardTitle>\n          <CardDescription>바이낸스 선물 상장 코인의 핵심 지표 표를 구성하는 중입니다. 다음 단계에서 시가총액, 공급량, 거래량, 펀딩비를 연결합니다.</CardDescription>\n        </CardHeader>\n        <CardContent className="rounded-3xl bg-slate-50 p-6 text-sm font-medium text-slate-600">\n          선물 상장 코인을 L1, L2, DeFi, AI, Meme, Infrastructure 등 섹터 관점으로 비교하도록 확장합니다.\n        </CardContent>\n      </Card>\n    </div>\n  );\n}\n''')
